// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using content;

namespace content.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190329161132_AddMonters")]
    partial class AddMonters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Auth0Example.Models.Monsters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CR");

                    b.Property<string>("Name");

                    b.Property<int>("TotalHealth");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CR = 5,
                            Name = "Ghoul",
                            TotalHealth = 26
                        },
                        new
                        {
                            Id = -2,
                            CR = 1,
                            Name = "Zombie",
                            TotalHealth = 6
                        },
                        new
                        {
                            Id = -3,
                            CR = 5,
                            Name = "Carrion Crow",
                            TotalHealth = 30
                        },
                        new
                        {
                            Id = -4,
                            CR = 8,
                            Name = "Chimera",
                            TotalHealth = 125
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
